const app = document.querySelector('#app');
const toastRegion = document.querySelector('#toast-region');
const API = window.location.port === '8000' ? 'app.php' : 'http://127.0.0.1:8000/app.php';
const demoKey = 'nexahire-demo';
const seedJobs = [
  { id: 1, title: 'Senior Product Designer', company_name: 'Luma Labs', location: 'Bengaluru, India', work_mode: 'Hybrid', employment_type: 'Full-time', salary_range: '₹24L - ₹32L', description: 'Shape delightful tools for teams building the future of work.', skills: ['Product design', 'Figma', 'Research'], status: 'Active', applicant_count: 12 },
  { id: 2, title: 'Frontend Engineer', company_name: 'Northstar Studio', location: 'Remote', work_mode: 'Remote', employment_type: 'Full-time', salary_range: '₹18L - ₹26L', description: 'Build crisp, accessible experiences with a thoughtful product team.', skills: ['React', 'TypeScript', 'CSS'], status: 'Active', applicant_count: 8 },
  { id: 3, title: 'Growth Marketing Intern', company_name: 'Clover Health', location: 'Mumbai, India', work_mode: 'On-site', employment_type: 'Internship', salary_range: '₹35K / month', description: 'Turn good ideas into measurable momentum for a growing health brand.', skills: ['Content', 'Analytics', 'SEO'], status: 'Active', applicant_count: 4 }
];
let state = { user: null, page: 'dashboard', role: 'user', authMode: 'login', destination: '', pendingOtp: null, jobs: [], applications: [], profile: null };

function readDemo() { return JSON.parse(localStorage.getItem(demoKey) || '{}'); }
function writeDemo(data) { localStorage.setItem(demoKey, JSON.stringify(data)); }
function demoData() { const d = readDemo(); return { users: d.users || [], jobs: d.jobs || seedJobs, applications: d.applications || [] }; }
function initials(name = 'N') { return name.split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase(); }
function esc(text = '') { return String(text).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c])); }
function toast(message, error = false) { const node = document.createElement('div'); node.className = `toast${error ? ' error' : ''}`; node.textContent = message; toastRegion.appendChild(node); setTimeout(() => node.remove(), 4200); }
async function api(action, payload = {}, method = 'POST') {
  try {
    const response = await fetch(`${API}?action=${action}`, { method, credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: method === 'GET' ? undefined : JSON.stringify(payload) });
    const body = await response.text();
    let data;
    try { data = body ? JSON.parse(body) : {}; } catch (parseError) { const error = new Error(`Invalid API response: ${response.status} ${response.headers.get('content-type') || 'unknown content type'} from ${response.url}. Open http://127.0.0.1:8000/ and refresh.`); error.apiError = true; throw error; }
    if (!response.ok) { const error = new Error(data.error || `Request failed (${response.status}).`); error.apiError = true; throw error; }
    return data;
  } catch (error) { if (error.apiError || action === 'request_otp' || action === 'verify_otp') throw error; if (location.protocol !== 'file:' && action !== 'jobs') console.info('Using demo mode:', error.message); return demoApi(action, payload); }
}
function demoApi(action, payload) {
  const d = demoData();
  if (action === 'request_otp') { state.pendingOtp = String(Math.floor(100000 + Math.random() * 900000)); state.pendingOtpExpiresAt = Date.now() + 5 * 60 * 1000; return { message: `OTP generated for ${payload.destination}.` }; }
  if (action === 'verify_otp') { if (payload.code !== state.pendingOtp || Date.now() > state.pendingOtpExpiresAt) throw new Error('That OTP is invalid or expired.'); const match = d.users.find(u => u.email === payload.destination || u.phone === payload.destination); return { verified: true, user: match || null }; }
  if (action === 'register') { const user = { id: Date.now(), role: payload.role, full_name: payload.full_name, email: payload.email, phone: payload.phone, headline: payload.role === 'employer' ? 'Hiring team' : 'Open to new opportunities', location: payload.location, bio: '', skills: [] }; d.users.push(user); writeDemo(d); return { user }; }
  if (action === 'login') { const match = d.users.find(u => u.email === payload.destination || u.phone === payload.destination); if (!match) throw new Error('Demo account not found. Create an account first.'); return { user: match }; }
  if (action === 'jobs') return { jobs: d.jobs };
  if (action === 'my_jobs') return { jobs: d.jobs.filter(j => j.employer_id === state.user.id) };
  if (action === 'job') { const job = { ...payload, id: Date.now(), employer_id: state.user.id, status: 'Active', applicant_count: 0, skills: payload.skills.split(',').map(s => s.trim()).filter(Boolean) }; d.jobs.unshift(job); writeDemo(d); return { message: 'Job posted successfully.' }; }
  if (action === 'apply') { d.applications.push({ id: Date.now(), job_id: payload.job_id, user_id: state.user.id, title: d.jobs.find(j => j.id == payload.job_id)?.title || 'Job', company_name: d.jobs.find(j => j.id == payload.job_id)?.company_name || '', status: 'Applied', applied_at: new Date().toISOString() }); writeDemo(d); return { message: 'Application submitted.' }; }
  if (action === 'applications') return { applications: d.applications.filter(a => state.role === 'employer' ? d.jobs.some(j => j.id === a.job_id && j.employer_id === state.user.id) : a.user_id === state.user.id) };
  if (action === 'profile') { if (payload && Object.keys(payload).length) { Object.assign(state.user, payload, { skills: payload.skills.split(',').map(s => s.trim()).filter(Boolean) }); const index = d.users.findIndex(u => u.id === state.user.id); if (index >= 0) d.users[index] = state.user; writeDemo(d); return { message: 'Profile updated.' }; } return { user: state.user }; }
  if (action === 'logout') return { logged_out: true };
  return {};
}

function renderAuth() {
  const isRegister = state.authMode === 'register'; const isOtp = state.authMode === 'otp';
  app.innerHTML = `<main class="auth-page"><section class="auth-visual"><div class="brand"><i class="brand-mark"></i><span>NexaHire</span></div><div class="visual-copy"><span class="eyebrow">Career, considered</span><h1>Find work that moves you.</h1><p>One calm, considered place for ambitious people and the teams building what is next.</p></div><div class="stat-strip"><div class="stat"><strong>18k+</strong><span>open roles</span></div><div class="stat"><strong>4.9/5</strong><span>candidate rating</span></div><div class="stat"><strong>72h</strong><span>average response</span></div></div></section><section class="auth-panel"><div class="auth-card"><div class="role-toggle"><button class="${state.role === 'user' ? 'active' : ''}" data-role="user">I’m looking for work</button><button class="${state.role === 'employer' ? 'active' : ''}" data-role="employer">I’m hiring</button></div>${isOtp ? otpMarkup() : isRegister ? registerMarkup() : loginMarkup()}</div></section></main>`;
  bindAuth();
}
function loginMarkup() { return `<span class="eyebrow">Welcome back</span><h2>Sign in to NexaHire</h2><p>Pick up where you left off and keep your next move moving.</p><form id="login-form"><label class="form-field"><span>Email or mobile number</span><input required name="destination" placeholder="you@example.com or +91 98765 43210" /></label><label class="form-field"><span>Password</span><input required type="password" name="password" placeholder="Your password" /></label><div class="auth-links"><button type="button" class="text-link" data-action="forgot">Forgot password?</button><button type="button" class="text-link" data-action="otp-start">Use OTP instead</button></div><button class="btn btn-primary">Sign in</button></form><div class="divider">or</div><p style="text-align:center;font-size:13px">New to NexaHire? <button class="text-link" data-action="register">Create an account</button></p>`; }
function registerMarkup() { return `<span class="eyebrow">Start your next chapter</span><h2>Create your account</h2><p>${state.role === 'employer' ? 'Bring your next great hire into focus.' : 'Make your next opportunity easier to find.'}</p><form id="register-form"><div class="form-grid"><label class="form-field"><span>Full name</span><input required name="full_name" placeholder="Zoya Khan" /></label><label class="form-field"><span>Location</span><input name="location" placeholder="Bengaluru, India" /></label></div><label class="form-field"><span>Email address</span><input required type="email" name="email" placeholder="you@example.com" /></label><label class="form-field"><span>Mobile number <small>(optional)</small></span><input name="phone" placeholder="+91 98765 43210" /></label><label class="form-field"><span>Create a password</span><input required type="password" name="password" placeholder="Choose any password" /></label><button class="btn btn-primary">Create ${state.role === 'employer' ? 'employer' : 'user'} account</button></form><p style="text-align:center;font-size:13px;margin-top:22px">Already have an account? <button class="text-link" data-action="login">Sign in</button></p>`; }
function otpMarkup() { return `<span class="eyebrow">Secure sign in</span><h2>Enter your OTP</h2><p>We sent a six-digit code to <strong>${esc(state.destination)}</strong>. It expires in 5 minutes.</p><form id="otp-form"><div class="otp-grid">${[0,1,2,3,4,5].map(i => `<input required maxlength="1" inputmode="numeric" data-otp="${i}" />`).join('')}</div><button class="btn btn-primary">Verify and continue</button></form><div class="auth-links"><button class="text-link" data-action="resend">Resend OTP</button><button class="text-link" data-action="login">Use password instead</button></div>`; }
function bindAuth() {
  document.querySelectorAll('[data-role]').forEach(b => b.onclick = () => { state.role = b.dataset.role; renderAuth(); });
  document.querySelectorAll('[data-action]').forEach(b => b.onclick = () => authAction(b.dataset.action));
  const login = document.querySelector('#login-form'); if (login) login.onsubmit = async e => { e.preventDefault(); const f = new FormData(login); const credentials = Object.fromEntries(f); try { const result = await api('login', credentials); if (state.role === 'employer' && result.user?.role !== 'employer') throw new Error('This account is registered as a candidate. Create or use an employer account to post jobs.'); state.destination = credentials.destination; state.user = result.user; state.role = result.user?.role || state.role; const otp = await api('request_otp', { destination: state.destination }); state.authMode = 'otp'; renderAuth(); toast(otp.message); } catch (err) { toast(err.message, true); } };
  const register = document.querySelector('#register-form'); if (register) register.onsubmit = async e => { e.preventDefault(); const f = new FormData(register); try { const result = await api('register', { ...Object.fromEntries(f), role: state.role }); state.user = result.user; enterApp(); toast('Your account is ready.'); } catch (err) { toast(err.message, true); } };
  const otp = document.querySelector('#otp-form'); if (otp) { document.querySelectorAll('[data-otp]').forEach((input, index, all) => input.oninput = () => { if (input.value && all[index + 1]) all[index + 1].focus(); }); otp.onsubmit = async e => { e.preventDefault(); const code = [...document.querySelectorAll('[data-otp]')].map(x => x.value).join(''); try { const result = await api('verify_otp', { destination: state.destination, code }); if (!result.user) { state.authMode = 'register'; renderAuth(); toast('OTP verified. Finish creating your account.'); } else { state.user = result.user; state.role = result.user.role; enterApp(); } } catch (err) { toast(err.message, true); } }; }
}
async function authAction(action) { if (action === 'register') { state.authMode = 'register'; renderAuth(); } else if (action === 'login') { state.authMode = 'login'; renderAuth(); } else if (action === 'forgot' || action === 'otp-start' || action === 'resend') { if (action !== 'resend') { const destination = prompt('Enter your email or mobile number'); if (!destination) return; state.destination = destination; } try { const result = await api('request_otp', { destination: state.destination }); state.authMode = 'otp'; renderAuth(); toast(result.message); } catch (err) { toast(err.message, true); } } }
function enterApp() { state.page = 'dashboard'; renderApp(); }
function navItems() { return state.role === 'employer' ? [['dashboard', '▦', 'Dashboard'], ['my-jobs', '▤', 'My Jobs'], ['applicants', '♙', 'Applicants'], ['profile', '◎', 'Profile']] : [['dashboard', '▦', 'Dashboard'], ['search', '⌕', 'Search jobs'], ['applications', '◷', 'My applications'], ['profile', '◎', 'Profile']]; }
async function renderApp() { const display = state.user || { full_name: 'Zoya Khan', email: 'zoya@example.com', role: state.role }; app.innerHTML = `<div class="app-layout"><aside class="sidebar"><div class="brand"><i class="brand-mark"></i><span>NexaHire</span></div><nav class="sidebar-nav"><span class="nav-label">Workspace</span>${navItems().map(([id, icon, label]) => `<button class="${state.page === id ? 'active' : ''}" data-page="${id}">${icon} <span>${label}</span></button>`).join('')}</nav><div class="sidebar-footer"><div class="user-mini"><div class="avatar">${initials(display.full_name)}</div><div><strong>${esc(display.full_name)}</strong><span>${state.role === 'employer' ? 'Employer' : 'Candidate'}</span></div></div><button class="sidebar-nav button" data-logout style="width:100%;border:0;background:transparent;color:rgba(255,255,255,.55);padding:12px;text-align:left">↪ <span>Log out</span></button></div></aside><main class="main-content"><header class="topbar"><div><h1>${pageTitle()}</h1><p>${pageSubtitle()}</p></div><div class="topbar-actions"><button class="icon-btn" title="Notifications">♢</button>${state.role === 'employer' ? '<button class="btn btn-dark" data-open-post>+ Post a job</button>' : ''}</div></header><section class="page-section" id="page-content"><div class="empty-state">Loading your workspace...</div></section></main></div>`; document.querySelectorAll('[data-page], [data-page-link]').forEach(b => b.onclick = e => { e.preventDefault(); state.page = b.dataset.page || b.dataset.pageLink; renderApp(); }); document.querySelector('[data-logout]').onclick = async () => { await api('logout'); state = { user: null, page: 'dashboard', role: 'user', authMode: 'login', destination: '', pendingOtp: null, jobs: [], applications: [], profile: null }; renderAuth(); }; const post = document.querySelector('[data-open-post]'); if (post) post.onclick = () => openPostModal(); await renderPage(); }
function pageTitle() { return ({ dashboard: 'Good morning, ' + (state.user?.full_name?.split(' ')[0] || 'Zoya'), 'my-jobs': 'My jobs', applicants: 'Applicants', search: 'Find your next role', applications: 'My applications', profile: 'Profile' })[state.page]; }
function pageSubtitle() { return ({ dashboard: state.role === 'employer' ? 'A clear view of your hiring momentum.' : 'A clear view of your career momentum.', 'my-jobs': 'Every opportunity you have put into the world.', applicants: 'Meet the people ready for their next move.', search: 'Thoughtful roles from teams worth joining.', applications: 'Keep every application in one calm place.', profile: 'Keep your details current and discoverable.' })[state.page]; }
async function renderPage() { const container = document.querySelector('#page-content'); if (state.page === 'dashboard') return renderDashboard(container); if (state.page === 'search') return renderSearch(container); if (state.page === 'my-jobs') return renderMyJobs(container); if (state.page === 'applicants' || state.page === 'applications') return renderApplications(container); if (state.page === 'profile') return renderProfile(container); }
async function getJobs(action = 'jobs') {
  const result = await api(action, {}, 'GET');
  state.jobs = (result.jobs || []).map(j => {
    let skills = j.skills;
    if (!Array.isArray(skills)) {
      try { skills = JSON.parse(skills || '[]'); } catch (e) { skills = []; }
    }
    return { ...j, skills };
  });
  return state.jobs;
}
async function renderDashboard(container) { const jobs = await getJobs(state.role === 'employer' ? 'my_jobs' : 'jobs'); const applications = (await api('applications', {}, 'GET')).applications || []; state.applications = applications; if (state.role === 'employer') { container.innerHTML = `<div class="hero-banner"><h2>Build the team that makes the impossible look easy.</h2><p>Your hiring workspace is ready. Share a role, track interest, and meet your next great teammate.</p></div><div class="metrics"><div class="metric-card"><span>Active jobs</span><strong>${jobs.filter(j => j.status === 'Active').length}</strong></div><div class="metric-card"><span>Total applicants</span><strong>${jobs.reduce((n, j) => n + Number(j.applicant_count || 0), 0)}</strong></div><div class="metric-card"><span>Profile views</span><strong>1,284</strong></div></div><div class="content-grid"><div class="surface"><div class="surface-head"><h3>Recent job posts</h3><a href="#" data-page-link="my-jobs">View all</a></div>${jobRows(jobs.slice(0, 3), true)}</div><div class="surface"><div class="surface-head"><h3>Hiring pulse</h3></div><div class="empty-state" style="padding-top:16px">Your candidates are waiting for a thoughtful first reply.</div></div></div>`; } else { container.innerHTML = `<div class="hero-banner"><h2>Your next chapter is closer than you think.</h2><p>Explore roles that match your ambition, values, and the way you want to work.</p></div><div class="metrics"><div class="metric-card"><span>Saved roles</span><strong>06</strong></div><div class="metric-card"><span>Applications sent</span><strong>${applications.length}</strong></div><div class="metric-card"><span>Profile strength</span><strong>82%</strong></div></div><div class="content-grid"><div class="surface"><div class="surface-head"><h3>Recommended for you</h3><a href="#" data-page-link="search">Explore all</a></div>${jobRows(jobs.slice(0, 3))}</div><div class="surface"><div class="surface-head"><h3>Make your profile work harder</h3></div><p style="color:var(--muted);font-size:13px;line-height:1.6">A complete profile gets more thoughtful responses from the teams you want to meet.</p><button class="btn btn-quiet" data-page-link="profile">Complete profile</button></div></div>`; } document.querySelectorAll('[data-page-link]').forEach(b => b.onclick = e => { e.preventDefault(); state.page = b.dataset.pageLink; renderApp(); }); }
function jobRows(jobs, employer = false) { return jobs.length ? jobs.map(j => `<div class="job-card"><div><h4>${esc(j.title)}</h4><p>${esc(j.company_name || j.employer_name || '')} · ${esc(j.location || '')}</p><div class="job-meta"><span class="tag">${esc(j.work_mode || 'Active')}</span><span class="tag">${esc(j.employment_type || 'Full-time')}</span></div></div><div style="text-align:right"><span class="status active">${employer ? `${j.applicant_count || 0} applicants` : esc(j.salary_range || 'View role')}</span></div></div>`).join('') : '<div class="empty-state">Nothing here yet.</div>'; }
async function renderSearch(container) { const jobs = await getJobs(); container.innerHTML = `<div class="search-bar"><input id="job-search" placeholder="Search by role, skill, or company" /><button class="btn btn-dark">Search</button></div><div class="surface"><div class="surface-head"><h3>${jobs.length} roles worth a closer look</h3><span style="color:var(--muted);font-size:12px">Updated just now</span></div><div id="search-results">${listingRows(jobs)}</div></div>`; const input = document.querySelector('#job-search'); input.oninput = () => { const q = input.value.toLowerCase(); document.querySelector('#search-results').innerHTML = listingRows(jobs.filter(j => `${j.title} ${j.company_name} ${j.location} ${(j.skills || []).join(' ')}`.toLowerCase().includes(q))); }; }
function listingRows(jobs) { return jobs.length ? jobs.map(j => `<article class="job-listing"><div><h3>${esc(j.title)}</h3><div class="company">${esc(j.company_name)} · ${esc(j.location)} · ${esc(j.work_mode)}</div><div class="job-meta">${(j.skills || []).map(s => `<span class="tag">${esc(s)}</span>`).join('')}</div></div><button class="btn btn-quiet" data-apply="${j.id}">View & apply</button></article>`).join('') : '<div class="empty-state">No roles match that search.</div>'; }
async function renderMyJobs(container) { const jobs = await getJobs('my_jobs'); container.innerHTML = `<div class="surface"><div class="surface-head"><h3>Your job posts</h3><button class="btn btn-dark" data-open-post>+ Post a job</button></div>${jobRows(jobs, true)}</div>`; document.querySelector('[data-open-post]').onclick = openPostModal; }
async function renderApplications(container) { const apps = (await api('applications', {}, 'GET')).applications || []; state.applications = apps; const employer = state.role === 'employer'; container.innerHTML = `<div class="surface"><div class="surface-head"><h3>${employer ? 'Candidate pipeline' : 'Application history'}</h3><span style="color:var(--muted);font-size:12px">${apps.length} total</span></div>${apps.length ? `<div class="table-wrap"><table><thead><tr>${employer ? '<th>Candidate</th><th>Role</th><th>Skills</th>' : '<th>Role</th><th>Company</th><th>Applied</th>'}<th>Status</th></tr></thead><tbody>${apps.map(a => `<tr>${employer ? `<td><strong>${esc(a.full_name || 'Candidate')}</strong><br><small style="color:var(--muted)">${esc(a.email || '')}</small></td><td>${esc(a.title)}</td><td>${esc(Array.isArray(a.skills) ? a.skills.join(', ') : a.skills || '—')}</td>` : `<td><strong>${esc(a.title)}</strong></td><td>${esc(a.company_name || '')}</td><td>${new Date(a.applied_at).toLocaleDateString()}</td>`}<td><span class="status ${String(a.status || 'Applied').toLowerCase()}">${esc(a.status || 'Applied')}</span></td></tr>`).join('')}</tbody></table></div>` : '<div class="empty-state">Applications will appear here once you make your next move.</div>'}</div>`; }
async function renderProfile(container) { const profile = (await api('profile', {}, 'GET')).user || state.user; const skills = Array.isArray(profile.skills) ? profile.skills.join(', ') : profile.skills || ''; container.innerHTML = `<div class="profile-grid"><div class="surface"><div class="profile-header"><div class="avatar">${initials(profile.full_name)}</div><div><h2>${esc(profile.full_name)}</h2><p>${esc(profile.headline || 'Add a headline to help people find you')}</p></div></div><form id="profile-form"><div class="form-grid"><label class="form-field"><span>Full name</span><input required name="full_name" value="${esc(profile.full_name)}" /></label><label class="form-field"><span>Phone</span><input name="phone" value="${esc(profile.phone || '')}" /></label></div><label class="form-field"><span>Headline</span><input name="headline" value="${esc(profile.headline || '')}" placeholder="What do you do best?" /></label><label class="form-field"><span>Location</span><input name="location" value="${esc(profile.location || '')}" /></label><label class="form-field"><span>Skills <small>(comma separated)</small></span><input name="skills" value="${esc(skills)}" placeholder="Product design, Figma, Research" /></label><label class="form-field"><span>About you</span><textarea name="bio" rows="5" placeholder="A little about your experience and what you are looking for...">${esc(profile.bio || '')}</textarea></label><button class="btn btn-primary">Save profile</button></form></div><div class="surface"><div class="surface-head"><h3>Profile visibility</h3><span class="status active">Public</span></div><p style="color:var(--muted);font-size:13px;line-height:1.65">Your profile is visible to relevant ${state.role === 'employer' ? 'candidates' : 'employers'} on NexaHire. Keep it current so the right conversations find you.</p></div></div>`; document.querySelector('#profile-form').onsubmit = async e => { e.preventDefault(); const f = new FormData(e.target); try { await api('profile', Object.fromEntries(f)); Object.assign(state.user, Object.fromEntries(f)); toast('Profile saved.'); renderApp(); } catch (err) { toast(err.message, true); } }; }
function openPostModal() { const node = document.createElement('div'); node.className = 'modal-backdrop'; node.innerHTML = `<div class="modal"><div class="modal-head"><div><h2>Post a new role</h2><p>Give great people a reason to meet your team.</p></div><button class="close-btn" data-close>×</button></div><form id="post-form"><div class="form-grid"><label class="form-field"><span>Job title</span><input required name="title" placeholder="e.g. Product Designer" /></label><label class="form-field"><span>Company name</span><input required name="company_name" placeholder="Your company" /></label><label class="form-field"><span>Location</span><input required name="location" placeholder="Bengaluru or Remote" /></label><label class="form-field"><span>Work mode</span><select name="work_mode"><option>Remote</option><option selected>Hybrid</option><option>On-site</option></select></label><label class="form-field"><span>Employment type</span><select name="employment_type"><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option></select></label><label class="form-field"><span>Salary range</span><input name="salary_range" placeholder="₹18L - ₹26L" /></label></div><label class="form-field"><span>Skills <small>(comma separated)</small></span><input name="skills" placeholder="React, TypeScript, Figma" /></label><label class="form-field"><span>Role description</span><textarea required name="description" rows="5" placeholder="What will this person own? What makes your team special?"></textarea></label><button class="btn btn-primary">Publish job</button></form></div>`; document.body.appendChild(node); node.querySelector('[data-close]').onclick = () => node.remove(); node.onclick = e => { if (e.target === node) node.remove(); }; node.querySelector('#post-form').onsubmit = async e => { e.preventDefault(); try { await api('job', Object.fromEntries(new FormData(e.target))); node.remove(); toast('Your job is live.'); renderApp(); } catch (err) { toast(err.message, true); } }; }

document.addEventListener('click', e => { const apply = e.target.closest('[data-apply]'); if (apply) { const job = state.jobs.find(j => j.id == apply.dataset.apply); if (!job) return; if (confirm(`Apply for ${job.title} at ${job.company_name}?`)) api('apply', { job_id: job.id }).then(() => { toast('Application submitted.'); renderApp(); }).catch(err => toast(err.message, true)); } });
renderAuth();
